### PR TITLE
New Airline Theme

### PR DESCRIPTION
**Pull request by Mootikins**
Added a new Airline theme that makes it easier to see splits that are above/below each other, while
modifying part of the theme to better suit this change.

### CODE REVIEW

**Comment by Mootikins** [comment]
Wasn't sure if you wanted it in a different branch or master, so I defaulted to a separate branch. If you would like it in master I can do that.

**Comment by deviantfero** [comment]
hi, I would like to see a screenshot if you have one :)

**Comment by Mootikins** [comment]
image
That's with a mostly blue theme.
image
And a theme with some more variety.

**Comment by deviantfero** [comment]
pretty cool, thanks :D

**Pull request merged**
