### PR TITLE
Initial Version: Alternate Colorscheme based on the original Pywal Colorsheme

### PR DESCRIPTION
**Pull request by Mootikins**
I'm not a big fan of the WPGTK vim colorscheme (no offense). Adapted the Pywal colorscheme to the WPGTK colors, open to input.

### CODE REVIEW

**Comment by deviantfero** [comment]
None taken!
would you mind adding a screenshot here so I can take a look at the differences

**Comment by Mootikins** [comment]
2019-04-21-070203_1366x768_scrot
Sorry for delay. The differences are pretty severe, mostly because it is a near carbon copy of the Pywal colorscheme, just shifted many of the color points to use the brighter variants of colors when they are adjusted. I have not edited the Lightline theme yet, as I do not use it, so I can remove it if you'd prefer. I also did not add documentation to the ReadMe about it since I remember it actually being in the wiki.

EDIT: Also forgot to mention that I have some highlights set contrary to the colorscheme itself:
```
highlight VertSplit ctermbg=0 ctermfg=15 cterm=none
highlight MatchParen ctermfg=12 ctermbg=none cterm=reverse
highlight NonText ctermfg=8
highlight CursorLineNr ctermfg=15
highlight LineNr ctermfg=4
highlight CursorLine ctermbg=8 cterm=none
```

**Comment by deviantfero** [comment]
great, I'll keep it as an alternative theme and I'll state as such in the documentation, all I need to do is set `wpgtkAlt` instead of `wpgtk` right?

**Comment by Mootikins** [comment]
That is correct, shows up just like a normal theme with that name.

**Comment by deviantfero** [comment]
thanks for your contribution :+1:

**Pull request merged**
